#!/bin/bash
#SBATCH -A TG-CCR140008
#SBATCH -J dataproc           # job name
#SBATCH -o dataproc.stdout       # output and error file name (%j expands to jobID)
#SBATCH -n 1
#SBATCH -p gpu     # queue (partition) -- normal, development, etc.
#SBATCH -t 00:40:00        # run time (hh:mm:ss) - 6 hours
#SBATCH --mail-user=maxjiang93@gmail.com
#SBATCH --mail-type=begin  # email me when the job starts
#SBATCH --mail-type=end    # email me when the job finishes

module reset
module load gcc/4.9.1 cuda/8.0 cudnn/5.1 python/2.7.12 tensorflow-gpu/1.0.0

DATA_DIR=$WORK/data
python download_and_convert_data.py \
    --dataset_name=miniplaces \
    --dataset_dir="${DATA_DIR}"
